export const mealData = {
  monday: {
    breakfast: [
      { item: 'Pancakes', waste: '' },
      { item: 'Eggs', waste: '' },
      { item: 'Toast', waste: '' },
      { item: 'Bacon', waste: '' },
      { item: 'Oatmeal', waste: '' },
    ],
    lunch: [
      { item: 'Rice', waste: '' },
      { item: 'Chicken', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Soup', waste: '' },
      { item: 'Steak', waste: '' },
    ],
    dinner: [
      { item: 'Pasta', waste: '' },
      { item: 'Steak', waste: '' },
      { item: 'Vegetables', waste: '' },
      { item: 'Salmon', waste: '' },
      { item: 'Mashed Potatoes', waste: '' },
    ],
  },
  tuesday: {
    breakfast: [
      { item: 'Omelette', waste: '' },
      { item: 'Bacon', waste: '' },
      { item: 'Toast', waste: '' },
      { item: 'Bagels', waste: '' },
      { item: 'Muffins', waste: '' },
    ],
    lunch: [
      { item: 'Burger', waste: '' },
      { item: 'Fries', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Grilled Cheese', waste: '' },
      { item: 'Pizza', waste: '' },
    ],
    dinner: [
      { item: 'Fish', waste: '' },
      { item: 'Rice', waste: '' },
      { item: 'Broccoli', waste: '' },
      { item: 'Grilled Chicken', waste: '' },
      { item: 'Vegetables', waste: '' },
    ],
  },
  wednesday: {
    breakfast: [
      { item: 'Pancakes', waste: '' },
      { item: 'Fruit Salad', waste: '' },
      { item: 'Yogurt', waste: '' },
      { item: 'Cereal', waste: '' },
      { item: 'Toast with Avocado', waste: '' },
    ],
    lunch: [
      { item: 'Pizza', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Garlic Bread', waste: '' },
      { item: 'Pasta', waste: '' },
      { item: 'Sushi', waste: '' },
    ],
    dinner: [
      { item: 'Spaghetti', waste: '' },
      { item: 'Meatballs', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Grilled Veggies', waste: '' },
      { item: 'Chicken Stir Fry', waste: '' },
    ],
  },
  thursday: {
    breakfast: [
      { item: 'French Toast', waste: '' },
      { item: 'Bacon', waste: '' },
      { item: 'Eggs', waste: '' },
      { item: 'Fruit Salad', waste: '' },
      { item: 'Toast with Butter', waste: '' },
    ],
    lunch: [
      { item: 'Chicken Wrap', waste: '' },
      { item: 'Potato Salad', waste: '' },
      { item: 'Coleslaw', waste: '' },
      { item: 'Caesar Salad', waste: '' },
      { item: 'Sandwich', waste: '' },
    ],
    dinner: [
      { item: 'Grilled Salmon', waste: '' },
      { item: 'Roasted Potatoes', waste: '' },
      { item: 'Asparagus', waste: '' },
      { item: 'Rice Pilaf', waste: '' },
      { item: 'Steak with Vegetables', waste: '' },
    ],
  },
  friday: {
    breakfast: [
      { item: 'Waffles', waste: '' },
      { item: 'Bacon', waste: '' },
      { item: 'Smoothie', waste: '' },
      { item: 'Toast', waste: '' },
      { item: 'Granola', waste: '' },
    ],
    lunch: [
      { item: 'Tacos', waste: '' },
      { item: 'Rice', waste: '' },
      { item: 'Guacamole', waste: '' },
      { item: 'Churros', waste: '' },
      { item: 'Pasta Salad', waste: '' },
    ],
    dinner: [
      { item: 'Lasagna', waste: '' },
      { item: 'Garlic Bread', waste: '' },
      { item: 'Caesar Salad', waste: '' },
      { item: 'Fried Chicken', waste: '' },
      { item: 'Mashed Potatoes', waste: '' },
    ],
  },
  saturday: {
    breakfast: [
      { item: 'Pancakes', waste: '' },
      { item: 'Eggs', waste: '' },
      { item: 'Sausage', waste: '' },
      { item: 'Fruit Salad', waste: '' },
      { item: 'Toast with Jam', waste: '' },
    ],
    lunch: [
      { item: 'Chicken Sandwich', waste: '' },
      { item: 'Soup', waste: '' },
      { item: 'Fries', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Fish Tacos', waste: '' },
    ],
    dinner: [
      { item: 'Spaghetti Bolognese', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Steamed Vegetables', waste: '' },
      { item: 'Grilled Chicken', waste: '' },
      { item: 'Potato Wedges', waste: '' },
    ],
  },
  sunday: {
    breakfast: [
      { item: 'Egg Sandwich', waste: '' },
      { item: 'Fruit Juice', waste: '' },
      { item: 'Pancakes', waste: '' },
      { item: 'Toast with Butter', waste: '' },
      { item: 'Yogurt Parfait', waste: '' },
    ],
    lunch: [
      { item: 'BBQ Ribs', waste: '' },
      { item: 'Corn on the Cob', waste: '' },
      { item: 'Salad', waste: '' },
      { item: 'Grilled Veggies', waste: '' },
      { item: 'Chicken Wings', waste: '' },
    ],
    dinner: [
      { item: 'Grilled Shrimp', waste: '' },
      { item: 'Rice', waste: '' },
      { item: 'Steamed Broccoli', waste: '' },
      { item: 'Pasta Salad', waste: '' },
      { item: 'Grilled Steak', waste: '' },
    ],
  },
};